sudo: false
language: rust
matrix:
  fast_finish: true
  include:
    - rust: nightly
#    - rust: beta
#    - rust: stable

# add --no-run to disable output
script:
- cargo test --all --color=always -- --nocapture

cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev